#!/bin/bash

# .env 파일 생성
cat <<EOF > .env
SECRET=${SECRET}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
PORT=${PORT}
DATABASE_HOST=127.0.0.1
DATABASE_PORT=${DATABASE_PORT}
DATABASE_DB=${DATABASE_DB}
DATABASE_NAME=${DATABASE_NAME}
DATABASE_PASSWORD=${DATABASE_PASSWORD}
EOF


