version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    # hostname: mysql_server
    volumes:
      - ./tools/db/init:/docker-entrypoint-initdb.d
      - ./tools/db/my.cnf:/etc/mysql/my.cnf
      - /custom/newhome/shipcheck-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: shipcheck
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    network_mode: host # 호스트의 네트워크 모드로 설정
    deploy:
      resources:
        limits:
          memory: 300M
